name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: check out git repository
      uses: actions/checkout@v4
    - name: cache apt packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: apt-${{ matrix.os }}-${{ hashFiles('.github/workflows/build.yml') }}
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake ffmpeg libx264-dev x264 libopencv-dev libva-dev libsdl2-dev clang-tidy
    - name: configure
      run: mkdir -p build && cd build && cmake .. -DENABLE_CLANG_TIDY=ON
    - name: build
      run: cd build && cmake --build . -j $(nproc)
